config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
  delete '/tasks/:id', to: 'tasks#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_tasks, only: [:show, :update, :edit, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task.id)
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path(@task.id)
  end

  def edit
  end

  def destroy
    @task.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path
  end

  private

  def set_tasks
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container">
  <div class="wrapper-form">
    <%= form_for(@task) do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :details %>
        <%= f.text_field :details, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :completed %>
        <%= f.check_box :completed, class: 'form-control' %>
      </div>
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'All list', tasks_path, class: 'btn btn-success' %>
    <% end %></div>
</div>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<div class="container">
  <div class="wrapper-form tasks">
     <h1>All tasks</h1>
     <%= link_to 'New Task', new_task_path, class: 'btn btn-primary' %>
     <% @tasks.each do |task| %>
     <% if task.completed == true %>
       <p><%= link_to task.title, task_path(task.id)%> <i class="far fa-check-square"></i></p>
       <% else %>
       <p><%= link_to task.title, task_path(task.id)%> <i class="far fa-square"></i></p>
     <% end %>
     <% end %>
   </div>
</div>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="container">
 <div class="wrapper-form display">
  <h1 ><%= @task.title %></h1>
    <p><%= @task.details %></p>
     <%= link_to '', tasks_path, class: 'fas fa-list-ul' %>
     <%= link_to '', edit_task_path, class: 'fas fa-edit' %>
     <%= link_to '',destroy_path, method: :delete,
      data: { confirm: "Are you sure?" }, class: 'fas fa-trash-alt' %>
   </div>
   </p>
 </div>
</div>